### ISSUE TITLE
git repository is not clone to the correct directory name

### ISSUE THREAD

**Issue by olblak** [olblak/updatecli#112]
**Describe the bug**
The git scm create the wrong directory
```
    scm:
      git:
        url: "git@github.com:olblak/charts.git"
        branch: "master"
        user: "olblak"
        email: "me@olblak.com"
```
will be cloned to "/tmp/git@github.com:olblak/charts.git" where chart.git dirname is "git@github.com:olblak" 

**Expected behavior**
`git@github.com:olblak/charts.git` should be correctly escaped
