### ISSUE TITLE
[dockerImage] Support ghcr.io

### ISSUE THREAD

**Issue by olblak** [olblak/updatecli#114]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the new github docker registy instead of dockerhub

**Describe the solution you'd like**
```
conditions:
  ghcr:
    name: "Docker Image Published on Registry"
    kind: dockerImage
    spec:
      image: "olblak/updatecli"
      url: "ghcr.io"
```

**Additional context**
-
