### ISSUE TITLE
include sources from helm chart

### ISSUE THREAD

**Issue by jetersen** [olblak/updatecli#127]
**Is your feature request related to a problem? Please describe.**
Some helm charts do not always use the home value for the helm chart which makes it hard to view changes to the helm chart.
Include sources from the helm chart ie. https://github.com/prometheus-community/helm-charts/blob/64de2b8427eb41043a6160390ee9f36a12f04139/charts/kube-prometheus-stack/Chart.yaml#L18-L20
```yaml
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
home: https://github.com/prometheus-operator/kube-prometheus
```
