### ISSUE TITLE
Provide configuration templating

### ISSUE THREAD

**Issue by olblak** [olblak/updatecli#32]
Problem:
Currently, we can use environment variables to configure the behavior, useful to store secrets. The environment variable starting with `UPDATECLI_` followed by the capitalized key name, matches configuration key . This makes it cumbersome when we use the same value in multiple location as we have to create a lot of different environment variable. 

Solution:
It would simplify the management of configuration files if we use templating so we could follow DRY principles when it makes sense, especially for example to only define secrets like GitHub token.

Example

values.conf
```
github:
    token: XXX
```

updateCli.conf
```
source:
  kind: maven
  postfix: "-jdk11"
  spec:
    owner: "maven"
    url: "repo.jenkins-ci.org"
    repository: "releases"
    groupID: "org.jenkins-ci.main"
    artifactID: "jenkins-war"
conditions:
  docker:
    name: "Docker Image Published on Registry"
    kind: dockerImage
    spec:
      image: "jenkins/jenkins"
targets:
  imageTag:
    name: "Docker Image"
    kind: yaml
    spec:
      file: "charts/jenkins/values.yaml"
      key: "jenkins.master.imageTag"
    scm:
      github:
        user: "updatecli"
        email: "updatecli@olblak.com"
        owner: "jenkins-infra"
        repository: "charts"
        token: "{{ github.token }}"
        username: "olblak"
        branch: "master"
```
