### ISSUE TITLE
Add condition based on yaml key/value retrieved from SCM

### ISSUE THREAD

**Issue by olblak** [olblak/updatecli#59]
**Is your feature request related to a problem? Please describe.**

It would be useful to be notified when the target changed and doesn't represent.
For example in yaml we could have something like
```
- name: A
  version: 1
- name: B
  version: 2
```

which becomes 

```
- name: B
  version: 2
- name: A
  version: 1
```

**Describe the solution you'd like**
```
Condition:
  kind: yaml
   spec:
      file: "helmfile.d/jenkins.yaml"
      key: "releases[0].name"
      value: "jenkins"
    scm:
      github:
        user: "updatecli"
        email: "updatecli@olblak.com"
        owner: "jenkins-infra"
        repository: "charts"
        token: {{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}
        username: "username"
        branch: "master"
```
