### ISSUE TITLE
source prefix and postfix added to branch 🤯

### ISSUE THREAD

**Issue by jetersen** [olblak/updatecli#61]
**Describe the bug**

Perhaps prefix and postfix should not affect branch 😓

```
source:
  kind: githubRelease
  prefix: https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=
  spec:
    owner: "argoproj"
    repository: "argo-cd"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.user }}"
    version: "latest"
targets:
  argocd:
    name: argo-cd
    kind: yaml
    spec:
      file: kustomize/argo-cd/kustomization.yaml
      key: bases[0]
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "org"
        repository: "repo"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "main"
```

```
##########
# ARGOCD #
##########



SOURCE:
=======

✔ 'latest' github release version founded: v1.6.1


TARGETS:
========

Cloning git repository: https://github.com/siteimprove/coreinfra-k8s-configs.git
Downloaded in /tmp/siteimprove/coreinfra-k8s-configs/https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.6.1

Enumerating objects: 262, done.
Counting objects: 100% (262/262), done.
Compressing objects: 100% (195/195), done.
Total 3847 (delta 130), reused 181 (delta 67), pack-reused 3585

Checkout Git Branch: updatecli/argo-cd/https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.6.1

Something went wrong in target "argocd" :
open /tmp/siteimprove/coreinfra-k8s-configs/https:/github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.6.1/kustomize/argo-cd/kustomization.yaml: no such file or directory
```

The desired result is to end up with updated URL with the version fetched from the source.

```
bases:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.6.1
```
