### ISSUE TITLE
Add dockerfile condition/target

### ISSUE THREAD

**Issue by olblak** [olblak/updatecli#91]
## Objectif
[ ] Define rules to automatically update Dockerfile content.
[ ] Define target stage
[ ] Define condition stage

## Requirements:
It requires a local Dockerfile or from a SCM

Example: Considering the following Dockerfile, I  am looking to update the Jenkins version to its latest version.

.Dockerfile
```
FROM jenkins/jenkins:2.268

LABEL maintainer=me@example.com
LABEL \
  version: 2.268

USER root

RUN apt-get update && apt-get install -y ruby make more-thing-here
 drop back to the regular jenkins user - good practice

USER jenkins
```

## Configuration

An Updatecli config example, where we would have two kind of specs, one simple and a more advance.

Please note that the "Value" field is only used for the condition stage. The target stage set the value for the field `Value` based on the source definition like "get the latest version from a Github release".

### Basic

A basic spec would be: 
```
    spec:
      file: Dockerfile
      Instruction: FROM
      value: "jenkins/jenkins:2.270"
```
Where we specify the Dockerfile location, the instruction we are targeting, and then its value.
But sometimes we may have multiple instructions like multiple labels, and inside those instructions, we are targeting different elements which is why I am looking for a more advanced configuration.

### Advanced
So I am suggesting to also allow to provide "position" information as in the following example, where we test if the second "ENV" instruction has a field "version" at the first value of the ENV line so we could validate that we can update the next element in the target section

```
    spec:
      file: Dockerfile
      Instruction: ENV[1]
      Position: 0
      Value: version"
```

Another option would be to drop `Position` for using the "Instruction" as a two-dimensional array where the first element defines the instruction position and the second defines the element position inside that Instruction like:

```
    spec:
      file: Dockerfile
      Instruction: ENV[1][0]
      Value: version"
```

### Full configuration
The following example is a full updatecli pipeline that updates every Jenkins version used in the Dockerfile to the latest version available.

.dockerfile.tpl
```
source:
  name: Get Latest jenkinsci/jenkins release name
  kind: githubRelease
  spec:
    owner: "jenkinsci"
    repository" "jenkins"
    token: {{ requiredEnv UPDATECLI_GITHUB_TOKEN }}
    username: olblak
    version: latest
conditions:
  isLabelSet:
    name: Is LABEL version set?
    kind: dockerfile
    spec:
      file: Dockerfile
      Instruction: ENV[1]
      Position: 1
      Value: "version"
targets:
  setFrom:
    name: Set Label version
    kind: dockerfile
    prefix: "jenkins/jenkins:"
    postfix: "-jdk11"
    spec:
      file: Dockerfile
      Instruction: FROM
  setLabel:
    name: Set Label version
    kind: dockerfile
    spec:which has for consequence to
      file: Dockerfile
      Instruction: ENV[1]
      Position: 2 # if the pipeline condition name " Is LABEL version set?" succeed then we know that this value contains the version
```
If we run updatecli cli on the Dockerfile defined earlier, I would expect to generate the following file 
```
FROM jenkins/jenkins:2.269-jdk

LABEL maintainer=me@example.com
LABEL \
  version: 2.2269

USER root

RUN apt-get update && apt-get install -y ruby make more-thing-here
 drop back to the regular jenkins user - good practice

USER jenkins
```

## Implementation

I am currently experimenting with the moby Dockerfile parser from [here](github.com/moby/buildkit/frontend/dockerfile/parser)
The major limitation that I found is that the Dockerfile object doesn't contain the Dockerfile comments. It sighlty complicates target implementation as we must read a Dockerfile, modify the object in memory, and then rewrite the Dockerfile without losing comments.
Fortunately, the Dockerfile object contains the line position for every instruction based on the initial Dockerfile so we can rebuild the full Dockerfile using the initial file and the in-memory object.

Ideas from [Twitter](https://twitter.com/0lblak/status/1295682115544190978)

**Comment by olblak** [comment]
I just updated this issue to provide more informations.
I currently have a working prototype for the basic condition and I am gathering feedback for the "advanced" configuration. I haven't work yet on the target stage

@jetersen  any thoughts?

**Comment by olblak** [comment]
While I could easily implement a source stage to fetch a value from a Dockerfile, I just can't see a valid usage

**Comment by olblak** [comment]
I'll go with the second option which seems more natural to me

```
    spec:
      file: Dockerfile
      Instruction: ENV[1][0]
      Value: version"
```
