### ISSUE TITLE
Document how to use github action bot

### ISSUE THREAD

**Issue by jetersen** [olblak/updatecli#95]
Instead of using my own token. I wanted to use github action's token and actually have the bot post pull requests!
Which btw totally works.

Here is the `updateCli/values.yaml`
```yaml
github:
  user: "GitHub Actions"
  email: "41898282+github-actions[bot]@users.noreply.github.com"
  username: "github-actions"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "master"
  owner: "Specshell"
  repository: "specshell.software.k8s.config"
```

This is the `.github/workflows/updatecli.yaml`
```yaml
name: Update CLI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  update_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update CLI
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sSfL -o updatecli https://github.com/olblak/updatecli/releases/download/v0.0.20/updatecli.linux.amd64
          chmod +x ./updatecli
          ./updatecli diff --config ./updateCli/updateCli.d --values ./updateCli/values.yaml
          ./updatecli apply --config ./updateCli/updateCli.d --values ./updateCli/values.yaml
```

This works out like this: 
![image](https://user-images.githubusercontent.com/1661688/96448467-b7aa4500-1213-11eb-91c5-ef4f8c3a3f9f.png)

**Comment by olblak** [comment]
Thanks for the suggestion, I wanted to do that for a while but I didn't have the time to do experimentation

**Comment by jetersen** [comment]
@olblak I wonder if there was an option in updateCli to use an reference repository or working directory git repository with the github scm option to reduce the amount git cloning.

**Comment by jetersen** [comment]
Reason I ask is `git cloning` happened 34 times in my case and that is where the majority of the time is spent.

**Comment by jetersen** [comment]
https://github.com/olblak/updatecli/tree/master/doc#github-action is missing an note on values that can be used:

```yaml
github:
  user: "GitHub Action"
  email: "41898282+github-actions[bot]@users.noreply.github.com"
  username: "github-actions"
  token: "UPDATECLI_GITHUB_TOKEN"
```
This avoids having a user and uses Github Action token provided but GitHub Action CI
