### ISSUE TITLE
the commit message seems to be off

### ISSUE THREAD

**Issue by jetersen** [olblak/updatecli#96]
**Describe the bug**
```
Key 'spec.template.spec.containers[0].image', from file 'apps/bitwarden/deployment.yaml', was updated to 'spec.template.spec.containers[0].image'
```

Shouldn't it be 
```
Key 'spec.template.spec.containers[0].image', from file 'apps/bitwarden/deployment.yaml', was updated to 'bitwardenrs/server:1.17.0'
```

`updatecli`
```yaml
source:
  kind: githubRelease
  spec:
    owner: "dani-garcia"
    repository: "bitwarden_rs"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.username }}"
    version: "latest"

conditions:
  docker:
    name: "Docker Image Published on Registry"
    kind: dockerImage
    spec:
      image: "bitwardenrs/server"

targets:
  imageTag:
    name: "bitwarden_rs"
    kind: yaml
    prefix: "bitwardenrs/server:"
    spec:
      prefix: "bitwardenrs/server:"
      file: "apps/bitwarden/deployment.yaml"
      key: "spec.template.spec.containers[0].image"
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
```

`deployment`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-k8s
  labels:
    app.kubernetes.io/name: bitwarden-k8s
    app.kubernetes.io/instance: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitwarden-k8s
      app.kubernetes.io/instance: bitwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitwarden-k8s
        app.kubernetes.io/instance: bitwarden
      annotations:
    spec:
      containers:
        - name: bitwarden-k8s
          image: "bitwardenrs/server:1.16.0"
          imagePullPolicy: IfNotPresent
          resources: {}
          env:
            - name: INVITATIONS_ALLOWED
              value: "false"
            - name: SIGNUPS_ALLOWED
              value: "true"
            - name: SIGNUPS_DOMAINS_WHITELIST
              value: "specshell.com"
            - name: DOMAIN
              value: https://bitwarden.specshell.net
            - name: ORG_CREATION_USERS
              value: jpe@specshell.net
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bitwarden-admin-token
                  key: token
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bitwarden-k8s
```
