### ISSUE TITLE
array position value is not updated.

### ISSUE THREAD

**Issue by jetersen** [olblak/updatecli#98]
For some reason the bases[0] is not updated.
The pull request is created with no file changes 😢 

This case is not working for me:

```yaml
source:
  kind: githubRelease
  spec:
    owner: "argoproj"
    repository: "argo-cd"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.username }}"
    version: "latest"
targets:
  argocd:
    name: argo-cd
    kind: yaml
    prefix: 'https://github.com/argoproj/argo-cd/manifests/cluster-install?ref='
    spec:
      prefix: 'https://github.com/argoproj/argo-cd/manifests/cluster-install?ref='
      file: "apps/argocd/kustomization.yaml"
      key: "bases[0]"
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
```

```yaml
namespace: argocd
bases:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.7.6
generatorOptions:
  disableNameSuffixHash: true
```

_Originally posted by @jetersen in https://github.com/olblak/updatecli/pull/97#issuecomment-712138374_
